const Result = [
  {
    first_name: "Marybeth",
    last_name: "Alans",
    score: 8.14,
    grade: 64,
    teacher_name: "Marybeth Alans",
  },
  {
    first_name: "Gery",
    last_name: "Starkey",
    score: 8.65,
    grade: 89,
    teacher_name: "Gery Starkey",
  },
  {
    first_name: "Hermon",
    last_name: "Danilowicz",
    score: 29.39,
    grade: 81,
    teacher_name: "Hermon Danilowicz",
  },
  {
    first_name: "Talyah",
    last_name: "Pavelin",
    score: 17.14,
    grade: 58,
    teacher_name: "Talyah Pavelin",
  },
  {
    first_name: "Piggy",
    last_name: "Fulep",
    score: 39.17,
    grade: 1,
    teacher_name: "Piggy Fulep",
  },
  {
    first_name: "Gay",
    last_name: "Domke",
    score: 73.9,
    grade: 29,
    teacher_name: "Gay Domke",
  },
  {
    first_name: "Cordey",
    last_name: "Vedmore",
    score: 15.56,
    grade: 1,
    teacher_name: "Cordey Vedmore",
  },
  {
    first_name: "Catina",
    last_name: "Beeke",
    score: 14.01,
    grade: 42,
    teacher_name: "Catina Beeke",
  },
  {
    first_name: "Kikelia",
    last_name: "Pettitt",
    score: 94.57,
    grade: 100,
    teacher_name: "Kikelia Pettitt",
  },
  {
    first_name: "Cale",
    last_name: "Buchanan",
    score: 23.64,
    grade: 16,
    teacher_name: "Cale Buchanan",
  },
  {
    first_name: "Erena",
    last_name: "Golborn",
    score: 25.68,
    grade: 2,
    teacher_name: "Erena Golborn",
  },
  {
    first_name: "Hart",
    last_name: "Alenichev",
    score: 77.08,
    grade: 48,
    teacher_name: "Hart Alenichev",
  },
  {
    first_name: "Eileen",
    last_name: "Guild",
    score: 76.63,
    grade: 80,
    teacher_name: "Eileen Guild",
  },
  {
    first_name: "Nadiya",
    last_name: "Huertas",
    score: 92.76,
    grade: 40,
    teacher_name: "Nadiya Huertas",
  },
  {
    first_name: "Iago",
    last_name: "Dolley",
    score: 28.6,
    grade: 27,
    teacher_name: "Iago Dolley",
  },
  {
    first_name: "Goddard",
    last_name: "Cliss",
    score: 88.78,
    grade: 75,
    teacher_name: "Goddard Cliss",
  },
  {
    first_name: "Maryl",
    last_name: "Eggerton",
    score: 72.0,
    grade: 14,
    teacher_name: "Maryl Eggerton",
  },
  {
    first_name: "Dalia",
    last_name: "Kiefer",
    score: 98.56,
    grade: 12,
    teacher_name: "Dalia Kiefer",
  },
  {
    first_name: "Chelsae",
    last_name: "Markova",
    score: 15.84,
    grade: 15,
    teacher_name: "Chelsae Markova",
  },
  {
    first_name: "Sammy",
    last_name: "Spackman",
    score: 62.54,
    grade: 49,
    teacher_name: "Sammy Spackman",
  },
  {
    first_name: "Kristin",
    last_name: "Lorriman",
    score: 70.04,
    grade: 82,
    teacher_name: "Kristin Lorriman",
  },
  {
    first_name: "Laraine",
    last_name: "Volker",
    score: 9.57,
    grade: 84,
    teacher_name: "Laraine Volker",
  },
  {
    first_name: "Doria",
    last_name: "Tuminini",
    score: 10.32,
    grade: 25,
    teacher_name: "Doria Tuminini",
  },
  {
    first_name: "Davita",
    last_name: "Weond",
    score: 99.44,
    grade: 23,
    teacher_name: "Davita Weond",
  },
  {
    first_name: "Cherish",
    last_name: "Eberst",
    score: 88.46,
    grade: 68,
    teacher_name: "Cherish Eberst",
  },
  {
    first_name: "Dinah",
    last_name: "Laxson",
    score: 9.78,
    grade: 79,
    teacher_name: "Dinah Laxson",
  },
  {
    first_name: "Jesse",
    last_name: "Haxell",
    score: 44.24,
    grade: 21,
    teacher_name: "Jesse Haxell",
  },
  {
    first_name: "Garnette",
    last_name: "Longo",
    score: 4.75,
    grade: 55,
    teacher_name: "Garnette Longo",
  },
  {
    first_name: "Lotta",
    last_name: "Haill",
    score: 64.82,
    grade: 65,
    teacher_name: "Lotta Haill",
  },
  {
    first_name: "Edwin",
    last_name: "Challice",
    score: 77.51,
    grade: 28,
    teacher_name: "Edwin Challice",
  },
  {
    first_name: "Rosella",
    last_name: "Berkowitz",
    score: 67.82,
    grade: 8,
    teacher_name: "Rosella Berkowitz",
  },
  {
    first_name: "Ailey",
    last_name: "Rubinovitsch",
    score: 51.06,
    grade: 70,
    teacher_name: "Ailey Rubinovitsch",
  },
  {
    first_name: "Paloma",
    last_name: "Meadowcraft",
    score: 58.31,
    grade: 79,
    teacher_name: "Paloma Meadowcraft",
  },
  {
    first_name: "Vail",
    last_name: "Sudell",
    score: 66.86,
    grade: 66,
    teacher_name: "Vail Sudell",
  },
  {
    first_name: "Neill",
    last_name: "Humpherston",
    score: 36.44,
    grade: 1,
    teacher_name: "Neill Humpherston",
  },
  {
    first_name: "Krispin",
    last_name: "Wilbore",
    score: 18.91,
    grade: 41,
    teacher_name: "Krispin Wilbore",
  },
  {
    first_name: "Montague",
    last_name: "Tanslie",
    score: 28.39,
    grade: 99,
    teacher_name: "Montague Tanslie",
  },
  {
    first_name: "Sinclair",
    last_name: "Heymes",
    score: 39.97,
    grade: 77,
    teacher_name: "Sinclair Heymes",
  },
  {
    first_name: "Ludwig",
    last_name: "MacDiarmid",
    score: 37.09,
    grade: 61,
    teacher_name: "Ludwig MacDiarmid",
  },
  {
    first_name: "Joe",
    last_name: "Graves",
    score: 2.58,
    grade: 4,
    teacher_name: "Joe Graves",
  },
  {
    first_name: "Fanni",
    last_name: "Ghidoni",
    score: 19.04,
    grade: 52,
    teacher_name: "Fanni Ghidoni",
  },
  {
    first_name: "Rosalia",
    last_name: "Breckenridge",
    score: 83.18,
    grade: 62,
    teacher_name: "Rosalia Breckenridge",
  },
  {
    first_name: "Miller",
    last_name: "Brain",
    score: 35.81,
    grade: 34,
    teacher_name: "Miller Brain",
  },
  {
    first_name: "Karla",
    last_name: "Ephson",
    score: 82.08,
    grade: 17,
    teacher_name: "Karla Ephson",
  },
  {
    first_name: "Jammie",
    last_name: "Bizley",
    score: 0.78,
    grade: 29,
    teacher_name: "Jammie Bizley",
  },
  {
    first_name: "Mariele",
    last_name: "Kruse",
    score: 26.31,
    grade: 16,
    teacher_name: "Mariele Kruse",
  },
  {
    first_name: "Marieann",
    last_name: "Romme",
    score: 31.35,
    grade: 39,
    teacher_name: "Marieann Romme",
  },
  {
    first_name: "Odelinda",
    last_name: "Skeemer",
    score: 7.12,
    grade: 71,
    teacher_name: "Odelinda Skeemer",
  },
  {
    first_name: "Alyson",
    last_name: "Slocum",
    score: 20.88,
    grade: 35,
    teacher_name: "Alyson Slocum",
  },
  {
    first_name: "Dorena",
    last_name: "Roskams",
    score: 58.19,
    grade: 50,
    teacher_name: "Dorena Roskams",
  },
  {
    first_name: "Darlleen",
    last_name: "Chieco",
    score: 95.6,
    grade: 88,
    teacher_name: "Darlleen Chieco",
  },
  {
    first_name: "Mahalia",
    last_name: "Sainsbury",
    score: 34.38,
    grade: 82,
    teacher_name: "Mahalia Sainsbury",
  },
  {
    first_name: "Tony",
    last_name: "Handasyde",
    score: 2.5,
    grade: 87,
    teacher_name: "Tony Handasyde",
  },
  {
    first_name: "Orazio",
    last_name: "Parslow",
    score: 31.97,
    grade: 57,
    teacher_name: "Orazio Parslow",
  },
  {
    first_name: "Babs",
    last_name: "Leggis",
    score: 75.72,
    grade: 69,
    teacher_name: "Babs Leggis",
  },
  {
    first_name: "Lorrie",
    last_name: "Gue",
    score: 54.23,
    grade: 78,
    teacher_name: "Lorrie Gue",
  },
  {
    first_name: "Nowell",
    last_name: "Rapson",
    score: 18.33,
    grade: 3,
    teacher_name: "Nowell Rapson",
  },
  {
    first_name: "Katti",
    last_name: "Monnery",
    score: 65.13,
    grade: 64,
    teacher_name: "Katti Monnery",
  },
  {
    first_name: "Garrik",
    last_name: "Crowcroft",
    score: 42.78,
    grade: 89,
    teacher_name: "Garrik Crowcroft",
  },
  {
    first_name: "Matt",
    last_name: "GiacobbiniJacob",
    score: 42.34,
    grade: 84,
    teacher_name: "Matt GiacobbiniJacob",
  },
  {
    first_name: "Bond",
    last_name: "Arlidge",
    score: 52.85,
    grade: 30,
    teacher_name: "Bond Arlidge",
  },
  {
    first_name: "Elaine",
    last_name: "Santo",
    score: 96.8,
    grade: 73,
    teacher_name: "Elaine Santo",
  },
  {
    first_name: "Hollis",
    last_name: "Berka",
    score: 8.4,
    grade: 60,
    teacher_name: "Hollis Berka",
  },
  {
    first_name: "Ronni",
    last_name: "Risson",
    score: 48.55,
    grade: 74,
    teacher_name: "Ronni Risson",
  },
  {
    first_name: "Jerome",
    last_name: "Yarr",
    score: 40.94,
    grade: 66,
    teacher_name: "Jerome Yarr",
  },
  {
    first_name: "Beatrix",
    last_name: "Keyte",
    score: 64.9,
    grade: 78,
    teacher_name: "Beatrix Keyte",
  },
  {
    first_name: "Giuseppe",
    last_name: "Huie",
    score: 63.96,
    grade: 97,
    teacher_name: "Giuseppe Huie",
  },
  {
    first_name: "Lyndsie",
    last_name: "Saffin",
    score: 26.77,
    grade: 20,
    teacher_name: "Lyndsie Saffin",
  },
  {
    first_name: "Lark",
    last_name: "Raymond",
    score: 60.42,
    grade: 33,
    teacher_name: "Lark Raymond",
  },
  {
    first_name: "Letizia",
    last_name: "Lovart",
    score: 51.49,
    grade: 47,
    teacher_name: "Letizia Lovart",
  },
  {
    first_name: "Brett",
    last_name: "Pafford",
    score: 27.16,
    grade: 95,
    teacher_name: "Brett Pafford",
  },
  {
    first_name: "Neron",
    last_name: "Tribell",
    score: 1.55,
    grade: 32,
    teacher_name: "Neron Tribell",
  },
  {
    first_name: "Humberto",
    last_name: "O' Byrne",
    score: 99.2,
    grade: 28,
    teacher_name: "Humberto O' Byrne",
  },
  {
    first_name: "Cece",
    last_name: "Hillam",
    score: 12.3,
    grade: 85,
    teacher_name: "Cece Hillam",
  },
  {
    first_name: "Anna-diana",
    last_name: "Masarrat",
    score: 94.82,
    grade: 56,
    teacher_name: "Anna-diana Masarrat",
  },
  {
    first_name: "Cy",
    last_name: "Lynnett",
    score: 39.12,
    grade: 8,
    teacher_name: "Cy Lynnett",
  },
  {
    first_name: "Zitella",
    last_name: "Birwhistle",
    score: 4.58,
    grade: 34,
    teacher_name: "Zitella Birwhistle",
  },
  {
    first_name: "Benton",
    last_name: "Glackin",
    score: 16.48,
    grade: 34,
    teacher_name: "Benton Glackin",
  },
  {
    first_name: "Gwenora",
    last_name: "Blamires",
    score: 60.63,
    grade: 61,
    teacher_name: "Gwenora Blamires",
  },
  {
    first_name: "Beniamino",
    last_name: "Ross",
    score: 79.18,
    grade: 94,
    teacher_name: "Beniamino Ross",
  },
  {
    first_name: "Cookie",
    last_name: "Bolzmann",
    score: 24.06,
    grade: 20,
    teacher_name: "Cookie Bolzmann",
  },
  {
    first_name: "Juana",
    last_name: "Churchley",
    score: 10.54,
    grade: 12,
    teacher_name: "Juana Churchley",
  },
  {
    first_name: "Talal",
    last_name: "ilyas",
    score: 10.54,
    grade: 12,
    teacher_name: "Amjad",
  },
];

const score = [
  {
    course_id: 1,
    course_title: "Honorable",
    awarded: 2.66,
    Credits: 47,
    score: 80,
  },
  { course_id: 2, course_title: "Dr", awarded: 4.33, Credits: 5, score: 62 },
  { course_id: 3, course_title: "Ms", awarded: 1.44, Credits: 36, score: 18 },
  { course_id: 4, course_title: "Mr", awarded: 2.45, Credits: 27, score: 2 },
  { course_id: 5, course_title: "Mr", awarded: 1.25, Credits: 65, score: 72 },
  { course_id: 6, course_title: "Mr", awarded: 3.17, Credits: 22, score: 41 },
  { course_id: 7, course_title: "Ms", awarded: 3.8, Credits: 41, score: 58 },
  { course_id: 8, course_title: "Rev", awarded: 4.29, Credits: 26, score: 58 },
  { course_id: 9, course_title: "Rev", awarded: 4.82, Credits: 3, score: 37 },
  { course_id: 10, course_title: "Mrs", awarded: 2.34, Credits: 35, score: 44 },
  { course_id: 11, course_title: "Mr", awarded: 3.29, Credits: 17, score: 86 },
  { course_id: 12, course_title: "Mr", awarded: 4.96, Credits: 77, score: 100 },
  {
    course_id: 13,
    course_title: "Honorable",
    awarded: 3.1,
    Credits: 75,
    score: 66,
  },
  { course_id: 14, course_title: "Mr", awarded: 4.23, Credits: 34, score: 43 },
  { course_id: 15, course_title: "Ms", awarded: 3.81, Credits: 72, score: 71 },
  { course_id: 16, course_title: "Rev", awarded: 3.27, Credits: 33, score: 75 },
  { course_id: 17, course_title: "Ms", awarded: 1.86, Credits: 20, score: 40 },
  { course_id: 18, course_title: "Mrs", awarded: 3.71, Credits: 39, score: 57 },
  { course_id: 19, course_title: "Mr", awarded: 2.75, Credits: 14, score: 76 },
  { course_id: 20, course_title: "Mrs", awarded: 2.35, Credits: 31, score: 17 },
  { course_id: 21, course_title: "Rev", awarded: 2.07, Credits: 54, score: 75 },
  { course_id: 22, course_title: "Mrs", awarded: 1.88, Credits: 26, score: 76 },
  { course_id: 23, course_title: "Ms", awarded: 4.04, Credits: 40, score: 10 },
  { course_id: 24, course_title: "Mr", awarded: 3.16, Credits: 65, score: 47 },
  { course_id: 25, course_title: "Dr", awarded: 4.06, Credits: 2, score: 1 },
  { course_id: 26, course_title: "Dr", awarded: 3.57, Credits: 90, score: 5 },
  { course_id: 27, course_title: "Mrs", awarded: 1.99, Credits: 39, score: 69 },
  { course_id: 28, course_title: "Mr", awarded: 1.27, Credits: 89, score: 34 },
  { course_id: 29, course_title: "Rev", awarded: 1.13, Credits: 13, score: 76 },
  { course_id: 30, course_title: "Mr", awarded: 2.84, Credits: 31, score: 10 },
  {
    course_id: 31,
    course_title: "Honorable",
    awarded: 4.44,
    Credits: 90,
    score: 71,
  },
  { course_id: 32, course_title: "Mrs", awarded: 4.13, Credits: 49, score: 93 },
  { course_id: 33, course_title: "Mrs", awarded: 3.52, Credits: 23, score: 31 },
  { course_id: 34, course_title: "Mrs", awarded: 2.17, Credits: 96, score: 56 },
  { course_id: 35, course_title: "Dr", awarded: 1.0, Credits: 78, score: 35 },
  { course_id: 36, course_title: "Rev", awarded: 4.98, Credits: 89, score: 25 },
  { course_id: 37, course_title: "Mrs", awarded: 1.67, Credits: 1, score: 57 },
  { course_id: 38, course_title: "Mrs", awarded: 4.84, Credits: 71, score: 38 },
  { course_id: 39, course_title: "Rev", awarded: 3.34, Credits: 79, score: 48 },
  { course_id: 40, course_title: "Rev", awarded: 3.38, Credits: 48, score: 89 },
  {
    course_id: 41,
    course_title: "Honorable",
    awarded: 3.94,
    Credits: 17,
    score: 87,
  },
  { course_id: 42, course_title: "Dr", awarded: 3.11, Credits: 32, score: 58 },
  { course_id: 43, course_title: "Rev", awarded: 4.08, Credits: 47, score: 44 },
  { course_id: 44, course_title: "Ms", awarded: 1.15, Credits: 94, score: 87 },
  { course_id: 45, course_title: "Mrs", awarded: 1.44, Credits: 55, score: 53 },
  { course_id: 46, course_title: "Mrs", awarded: 2.92, Credits: 66, score: 91 },
  { course_id: 47, course_title: "Mr", awarded: 3.08, Credits: 88, score: 76 },
  { course_id: 48, course_title: "Rev", awarded: 4.74, Credits: 7, score: 72 },
  {
    course_id: 49,
    course_title: "Honorable",
    awarded: 4.59,
    Credits: 49,
    score: 7,
  },
  { course_id: 50, course_title: "Rev", awarded: 2.44, Credits: 37, score: 1 },
  {
    course_id: 51,
    course_title: "Honorable",
    awarded: 1.79,
    Credits: 61,
    score: 94,
  },
  {
    course_id: 52,
    course_title: "Honorable",
    awarded: 1.41,
    Credits: 90,
    score: 90,
  },
  { course_id: 53, course_title: "Dr", awarded: 2.14, Credits: 33, score: 96 },
  {
    course_id: 54,
    course_title: "Honorable",
    awarded: 2.61,
    Credits: 27,
    score: 8,
  },
  {
    course_id: 55,
    course_title: "Honorable",
    awarded: 1.56,
    Credits: 73,
    score: 80,
  },
  { course_id: 56, course_title: "Dr", awarded: 4.09, Credits: 94, score: 43 },
  { course_id: 57, course_title: "Mrs", awarded: 4.4, Credits: 5, score: 97 },
  { course_id: 58, course_title: "Mrs", awarded: 2.24, Credits: 24, score: 4 },
  { course_id: 59, course_title: "Rev", awarded: 2.15, Credits: 44, score: 42 },
  { course_id: 60, course_title: "Ms", awarded: 3.32, Credits: 2, score: 50 },
  { course_id: 61, course_title: "Ms", awarded: 2.38, Credits: 90, score: 20 },
  {
    course_id: 62,
    course_title: "Honorable",
    awarded: 4.62,
    Credits: 90,
    score: 11,
  },
  { course_id: 63, course_title: "Mr", awarded: 4.4, Credits: 64, score: 12 },
  {
    course_id: 64,
    course_title: "Honorable",
    awarded: 2.28,
    Credits: 20,
    score: 29,
  },
  {
    course_id: 65,
    course_title: "Honorable",
    awarded: 2.3,
    Credits: 19,
    score: 25,
  },
  { course_id: 66, course_title: "Mrs", awarded: 4.57, Credits: 85, score: 82 },
  {
    course_id: 67,
    course_title: "Honorable",
    awarded: 2.91,
    Credits: 9,
    score: 70,
  },
  { course_id: 68, course_title: "Mr", awarded: 1.17, Credits: 90, score: 81 },
  { course_id: 69, course_title: "Rev", awarded: 3.45, Credits: 23, score: 55 },
  { course_id: 70, course_title: "Ms", awarded: 2.96, Credits: 93, score: 95 },
  { course_id: 71, course_title: "Ms", awarded: 1.5, Credits: 88, score: 15 },
  { course_id: 72, course_title: "Dr", awarded: 2.68, Credits: 22, score: 68 },
  { course_id: 73, course_title: "Dr", awarded: 1.45, Credits: 21, score: 100 },
  { course_id: 74, course_title: "Rev", awarded: 4.33, Credits: 26, score: 81 },
  { course_id: 75, course_title: "Ms", awarded: 3.61, Credits: 14, score: 16 },
  { course_id: 76, course_title: "Mr", awarded: 3.92, Credits: 57, score: 47 },
  { course_id: 77, course_title: "Ms", awarded: 1.23, Credits: 59, score: 98 },
  {
    course_id: 78,
    course_title: "Honorable",
    awarded: 1.23,
    Credits: 97,
    score: 13,
  },
  {
    course_id: 79,
    course_title: "Honorable",
    awarded: 1.77,
    Credits: 18,
    score: 65,
  },
  { course_id: 80, course_title: "Dr", awarded: 4.14, Credits: 8, score: 41 },
  {
    course_id: 81,
    course_title: "Mrs",
    awarded: 1.13,
    Credits: 100,
    score: 60,
  },
  { course_id: 82, course_title: "Mr", awarded: 4.67, Credits: 72, score: 47 },
  { course_id: 83, course_title: "Dr", awarded: 3.61, Credits: 47, score: 68 },
  { course_id: 84, course_title: "Dr", awarded: 2.33, Credits: 66, score: 85 },
  { course_id: 85, course_title: "Dr", awarded: 3.71, Credits: 39, score: 26 },
  {
    course_id: 86,
    course_title: "Honorable",
    awarded: 1.16,
    Credits: 95,
    score: 100,
  },
  { course_id: 87, course_title: "Dr", awarded: 2.56, Credits: 77, score: 72 },
  { course_id: 88, course_title: "Mrs", awarded: 3.9, Credits: 35, score: 41 },
  { course_id: 89, course_title: "Dr", awarded: 3.34, Credits: 15, score: 32 },
  { course_id: 90, course_title: "Mrs", awarded: 4.48, Credits: 12, score: 75 },
  { course_id: 91, course_title: "Rev", awarded: 1.34, Credits: 14, score: 72 },
  { course_id: 92, course_title: "Mrs", awarded: 2.36, Credits: 76, score: 37 },
  { course_id: 93, course_title: "Dr", awarded: 2.62, Credits: 36, score: 68 },
  { course_id: 94, course_title: "Mr", awarded: 3.58, Credits: 68, score: 17 },
  { course_id: 95, course_title: "Ms", awarded: 2.67, Credits: 60, score: 64 },
  { course_id: 96, course_title: "Dr", awarded: 4.15, Credits: 76, score: 27 },
  { course_id: 97, course_title: "Mr", awarded: 1.57, Credits: 96, score: 43 },
  {
    course_id: 98,
    course_title: "Honorable",
    awarded: 4.59,
    Credits: 1,
    score: 59,
  },
];

const mycourse = [
  {
    course_subject: "Mathematics",
    exam_type: "Practical",
    exam_date_time: "12/7/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Practical",
    exam_date_time: "8/27/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Practical",
    exam_date_time: "3/27/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Multiple Choice",
    exam_date_time: "12/2/2022",
  },
  {
    course_subject: "History",
    exam_type: "Essay",
    exam_date_time: "7/19/2022",
  },
  {
    course_subject: "History",
    exam_type: "Multiple Choice",
    exam_date_time: "10/7/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Multiple Choice",
    exam_date_time: "12/15/2022",
  },
  { course_subject: "Science", exam_type: "Essay", exam_date_time: "5/2/2022" },
  {
    course_subject: "Science",
    exam_type: "Multiple Choice",
    exam_date_time: "12/9/2022",
  },
  { course_subject: "Science", exam_type: "Essay", exam_date_time: "2/1/2022" },
  {
    course_subject: "History",
    exam_type: "Essay",
    exam_date_time: "10/3/2022",
  },
  {
    course_subject: "Mathematics",
    exam_type: "Practical",
    exam_date_time: "1/28/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Essay",
    exam_date_time: "12/18/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Multiple Choice",
    exam_date_time: "8/29/2022",
  },
  {
    course_subject: "Mathematics",
    exam_type: "Multiple Choice",
    exam_date_time: "8/23/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Multiple Choice",
    exam_date_time: "7/13/2022",
  },
  {
    course_subject: "Mathematics",
    exam_type: "Practical",
    exam_date_time: "4/12/2022",
  },
  {
    course_subject: "History",
    exam_type: "Multiple Choice",
    exam_date_time: "2/11/2022",
  },
  {
    course_subject: "History",
    exam_type: "Multiple Choice",
    exam_date_time: "2/4/2022",
  },
  {
    course_subject: "History",
    exam_type: "Multiple Choice",
    exam_date_time: "9/27/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Practical",
    exam_date_time: "5/16/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Practical",
    exam_date_time: "12/9/2022",
  },
  {
    course_subject: "Mathematics",
    exam_type: "Multiple Choice",
    exam_date_time: "5/31/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Multiple Choice",
    exam_date_time: "11/23/2022",
  },
  {
    course_subject: "Mathematics",
    exam_type: "Essay",
    exam_date_time: "12/11/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Multiple Choice",
    exam_date_time: "1/29/2022",
  },
  {
    course_subject: "History",
    exam_type: "Practical",
    exam_date_time: "11/11/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Practical",
    exam_date_time: "5/16/2022",
  },
  {
    course_subject: "Mathematics",
    exam_type: "Practical",
    exam_date_time: "9/4/2022",
  },
  {
    course_subject: "Mathematics",
    exam_type: "Essay",
    exam_date_time: "2/28/2022",
  },
  {
    course_subject: "Mathematics",
    exam_type: "Essay",
    exam_date_time: "12/17/2022",
  },
  {
    course_subject: "History",
    exam_type: "Essay",
    exam_date_time: "4/10/2022",
  },
  {
    course_subject: "History",
    exam_type: "Essay",
    exam_date_time: "4/26/2022",
  },
  { course_subject: "History", exam_type: "Essay", exam_date_time: "9/9/2022" },
  {
    course_subject: "History",
    exam_type: "Practical",
    exam_date_time: "12/5/2022",
  },
  {
    course_subject: "Science",
    exam_type: "Practical",
    exam_date_time: "11/12/2022",
  },
  {
    course_subject: "History",
    exam_type: "Practical",
    exam_date_time: "2/23/2022",
  },
  {
    course_subject: "History",
    exam_type: "Multiple Choice",
    exam_date_time: "5/31/2022",
  },
  {
    course_subject: "History",
    exam_type: "Multiple Choice",
    exam_date_time: "7/26/2022",
  },
  {
    course_subject: "History",
    exam_type: "Multiple Choice",
    exam_date_time: "9/9/2022",
  },
  {
    course_subject: "History",
    exam_type: "Essay",
    exam_date_time: "1/14/2022",
  },
];

const SpAnoucments = [
  {
    announcement_text:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
  },
  {
    announcement_text:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
  },
  {
    announcement_text:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
  },
  {
    announcement_text:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
  },
  {
    announcement_text:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
  },
  {
    announcement_text:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
  },
  {
    announcement_text:
      "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
  },
  {
    announcement_text:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
  },
  {
    announcement_text:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
  },
  {
    announcement_text:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
  },
];

const Label = [
  { id: 1, label: "Course Catalogue", path: "coursecatalogue" },
  { id: 2, label: "My Progress", path: "myprogress" },
  { id: 3, label: "Academic Calendar", path: "academiccalendar" },
  { id: 4, label: "Results Card", path: "resultcard" },
  { id: 5, label: "Study Card", path: "studycard" },
  { id: 6, label: "Recommendations", path: "recommendations" },
  { id: 7, label: "My Rating", path: "myrating" },
  { id: 8, label: "Sign Out", path: "" },
];

const userprofile = [
  {
    name: "John Doe",
    status: "Active",
    avatar: "public/image/images.jpg",
  },
];
const Progress = [
  { name: "Course A", type: "circle", percent: 90 },
  {
    name: "Course B",
    type: "circle",
    percent: 90,
  },
  {
    "name ": "Course C",
    type: "Circle",
    percent: 70,
  },
  {
    name: "Course",
    "type ": "Circle",
    percent: 60,
  },
];

const Calendar = [
  { date: "2025-07-05", type: "success", content: "Midterm Exams Start" },
  { date: "2025-07-12", type: "error", content: "Project Presentation" },
  { date: "2025-07-25", type: "success", content: "Final Exams Start" },
];
const studycard = [
  { id: 1, label: "Geography" ,color: "#fff9db" },

  { id: 2, label: "History" ,color: "#fbeaea" },

  { id: 3, label: "Biology"  , color: "#e8f7e4"},
 
  { id: 4, label: "Music", color: "#f0e9ff" },
  { id: 5, label: "Music", color: "#f0e9ff"  },
];
   const recommendations = [
    {  }
   ]
module.exports = {
  Result: Result,
  myresult: mycourse,
  score: score,
  studentResults: Result,
  studentcourse: mycourse,
  studentscore: score,

  ANoucments: SpAnoucments,

  label: Label,
  userprofile: userprofile,
  progress: Progress,
  Calendar: Calendar,
  studycard:studycard
};
